### ISSUE TITLE
Volume commands frequently don't work

### ISSUE THREAD

**Issue by Heathcliff77** [alphapapa/listen.el#26] opened 2024-04-26 09:41 UTC
I am frequently getting two issues related to the volume control.

1. `= Set volume` simply don't work. If I change volume between 10% and 100% there's no actual change in volume.

2. `V/v raise/lower volume` only works once. If I hit 'v' repeatedly, the volume% stays the same number. But if I switch between hitting v/V the volume% can be changed, but only one step in either direction.

System information: Emacs 29.3 (build 1, x86_64-redhat-linux-gnu, GTK+ Version 3.24.41, cairo version 1.17.8) of 2024-03-25 
vlc 3.0.20 Vetinari (revision 3.0.20-0-g6f0d0ab126b)

**Comment by alphapapa** [comment] 2024-04-26 20:26
I have the same software versions and it works fine for me.  Try to reproduce it in a clean Emacs configuration.

**Comment by alphapapa** [comment] 2024-06-05 17:37
Since I can't reproduce this, I'm closing this report.  If you can reproduce it and provide more information, please follow up.  Thanks.

**Closed by alphapapa** 2024-06-05 17:37 UTC

**Comment by pseudomyne** [comment] 2024-08-06 12:34
Hi. Just. Same issue here. Alas, no time / energy / knowledge to properly offer reproducable issue. (emacs 29.4, arch linux).
